name: Publish-Extension

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  build:
  # env:
  #   RELEASE: ${{startsWith(github.event.commits[0].message,'chore(release):')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install
      - name: Create Tag
        run: |
          git config user.email ${{ secrets.USER_EMAIL }}
          git config user.name ${{ secrets.USER_NAME }}
          yarn release
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
